---
# Variable configuration
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family != "RedHat"

- name: Include OS-specific variables (RHEL versions)
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_os_family == "RedHat"

- name: Define vim packages
  set_fact:
    vim_package: "{{ __vim_package | list }}"
  when: vim_package is not defined

- name: Install vim
  pkg:
    name: "{{vim_package}}"
    state: present
